version: '3.8'

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: dotnet_app
    ports:
      - "5000:80"
    volumes:
      - .:/app
    working_dir: /app
    command: ["dotnet", "run", "--urls", "http://*:80"]
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel_collector
    ports:
      - "4317:4317"
      - "55681:55681"
    volumes:
      - ./otel-collector-config.yml:/otel-local-config.yaml
    command: ["--config=/otel-local-config.yaml"]
