receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
  sampling:
    probabilistic:
      samplingRate: 0.5

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
